name: Test and Build

enable-openid-connect: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/go-setup@master
      - uses: actions/toolkit/go-test@master
  container:
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:4b63558b-45f2-4311-9921-14f47224392b
      - uses: actions/toolkit/docker-build@master
  release:
    if: github.ref_type == 'tag'
    runs-on: alpine
    needs:
      - test
      - container
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:4b63558b-45f2-4311-9921-14f47224392b
      - uses: actions/toolkit/docker-build@master
